### ISSUE TITLE
Example of duplicate timestamps found by running tests

### ISSUE THREAD

**Issue by julianharty** [commercetest/kafka-unit#2]
The `KafkaAssumptionsTest` class enables us to test assumptions on behaviours of Kafka. It contains a test `` that writes a configurable set of messages and then reads them back, checking for any duplicate timestamps. Sometimes it finds duplicates nearly every run, other times it runs without any duplicates being detected. 

Here's an example of a recent test run that wrote 1500 KeyedMessages and found a duplicate for messages 1122 and 1123. This issue is so it's easier to share and track the extent of the problem and see if any patterns emerge.

```
    2017-12-12 14:33:49 INFO  KafkaAssumptionsTest:71 - Msg[1120] timestamp[1513089219042]
    2017-12-12 14:33:49 INFO  KafkaAssumptionsTest:71 - Msg[1121] timestamp[1513089219044]
    2017-12-12 14:33:49 INFO  KafkaAssumptionsTest:71 - Msg[1122] timestamp[1513089219045]
    2017-12-12 14:33:49 INFO  KafkaAssumptionsTest:71 - Msg[1123] timestamp[1513089219045]
    2017-12-12 14:33:49 WARN  NetworkClient:241 - [Producer clientId=kafka-unit-producer] Connection to node 1 could not be established. Broker may not be available.
    2017-12-12 14:33:49 WARN  NetworkClient:241 - [Producer clientId=kafka-unit-producer] Connection to node 1 could not be established. Broker may not be available.
    2017-12-12 14:33:49 WARN  NetworkClient:241 - [Producer clientId=kafka-unit-producer] Connection to node 1 could not be established. Broker may not be available.
    2017-12-12 14:33:50 WARN  NetworkClient:241 - [Producer clientId=kafka-unit-producer] Connection to node 1 could not be established. Broker may not be available.
    2017-12-12 14:33:51 WARN  NetworkClient:241 - [Producer clientId=kafka-unit-producer] Connection to node 1 could not be established. Broker may not be available.
    2017-12-12 14:33:52 ERROR ZooKeeperServer:472 - ZKShutdownHandler is not registered, so ZooKeeper server won't take any action on ERROR or SHUTDOWN server state changes
Gradle Test Executor 1 finished executing tests.

info.batey.kafka.unit.KafkaAssumptionsTest > timestampsAreUniqueForOurMessages FAILED
    java.lang.AssertionError: Timestamp shouldn't be equal or less than previous value
    Expected: a value greater than <1513089219045L>
         but: <1513089219045L> was equal to <1513089219045L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at info.batey.kafka.unit.KafkaAssumptionsTest.timestampsAreUniqueForOurMessages(KafkaAssumptionsTest.java:73)
```

**Comment by julianharty** [comment]
The very next run found another duplicate:
```
    2017-12-12 14:44:53 INFO  KafkaAssumptionsTest:71 - Msg[928] timestamp[1513089886403]
    2017-12-12 14:44:53 INFO  KafkaAssumptionsTest:71 - Msg[929] timestamp[1513089886404]
    2017-12-12 14:44:53 INFO  KafkaAssumptionsTest:71 - Msg[930] timestamp[1513089886404]
    2017-12-12 14:44:54 WARN  NetworkClient:241 - [Producer clientId=kafka-unit-producer] Connection to node 1 could not be established. Broker may not be available.
-- cut --
    2017-12-12 14:44:56 ERROR ZooKeeperServer:472 - ZKShutdownHandler is not registered, so ZooKeeper server won't take any action on ERROR or SHUTDOWN server state changes
Gradle Test Executor 1 finished executing tests.

info.batey.kafka.unit.KafkaAssumptionsTest > timestampsAreUniqueForOurMessages FAILED
    java.lang.AssertionError: Timestamp shouldn't be equal or less than previous value
    Expected: a value greater than <1513089886404L>
         but: <1513089886404L> was equal to <1513089886404L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at info.batey.kafka.unit.KafkaAssumptionsTest.timestampsAreUniqueForOurMessages(KafkaAssumptionsTest.java:73)


```

**Comment by julianharty** [comment]
And the next (with the `log.segment.bytes` set to `131072` rather than `262144` previously).
```
    2017-12-12 14:47:09 INFO  KafkaAssumptionsTest:71 - Msg[1221] timestamp[1513090019349]
    2017-12-12 14:47:09 INFO  KafkaAssumptionsTest:71 - Msg[1222] timestamp[1513090019350]
    2017-12-12 14:47:09 INFO  KafkaAssumptionsTest:71 - Msg[1223] timestamp[1513090019350]
-- cut --
Gradle Test Executor 1 finished executing tests.

info.batey.kafka.unit.KafkaAssumptionsTest > timestampsAreUniqueForOurMessages FAILED
    java.lang.AssertionError: Timestamp shouldn't be equal or less than previous value
    Expected: a value greater than <1513090019350L>
         but: <1513090019350L> was equal to <1513090019350L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at info.batey.kafka.unit.KafkaAssumptionsTest.timestampsAreUniqueForOurMessages(KafkaAssumptionsTest.java:73)
```

**Comment by julianharty** [comment]
And another (this time I'd updated Zookeeper to `3.4.11` but I doubt that's important)
```
    2017-12-12 14:59:26 INFO  KafkaAssumptionsTest:70 - Msg[754] timestamp[1513090758816]
    2017-12-12 14:59:26 INFO  KafkaAssumptionsTest:70 - Msg[755] timestamp[1513090758817]
    2017-12-12 14:59:26 INFO  KafkaAssumptionsTest:70 - Msg[756] timestamp[1513090758817]
-- cut --
Gradle Test Executor 1 finished executing tests.

info.batey.kafka.unit.KafkaAssumptionsTest > timestampsAreUniqueForOurMessages FAILED
    java.lang.AssertionError: Timestamp shouldn't be equal or less than previous value
    Expected: a value greater than <1513090758817L>
         but: <1513090758817L> was equal to <1513090758817L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at info.batey.kafka.unit.KafkaAssumptionsTest.timestampsAreUniqueForOurMessages(KafkaAssumptionsTest.java:72)
```

**Comment by julianharty** [comment]
Experimented with the timeouts, they don't materially affect when duplicates occur from what I can tell. e.g.
```
    2017-12-12 15:32:06 INFO  KafkaAssumptionsTest:71 - Msg[1046] timestamp[1513092716315]
    2017-12-12 15:32:06 INFO  KafkaAssumptionsTest:71 - Msg[1047] timestamp[1513092716317]
    2017-12-12 15:32:06 INFO  KafkaAssumptionsTest:71 - Msg[1048] timestamp[1513092716317]
-- cut --
Gradle Test Executor 1 finished executing tests.

info.batey.kafka.unit.KafkaAssumptionsTest > timestampsAreUniqueForOurMessages FAILED
    java.lang.AssertionError: Timestamp shouldn't be equal or less than previous value
    Expected: a value greater than <1513092716317L>
         but: <1513092716317L> was equal to <1513092716317L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at info.batey.kafka.unit.KafkaAssumptionsTest.timestampsAreUniqueForOurMessages(KafkaAssumptionsTest.java:73)
```
